### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by rimiti**
Hello,

**Some improvements:**

- Force mocha to exit.
- sprintf-js + async + cookie-parser + express packages updated.
- package-lock.json tracked.
- CI fixed.
- CI updated for running tests on NodeJS Current + LTS (_io.js has merged with the Node.js project again. There won't be any further io.js releases. All of the features in io.js are available in Node.js v4 and above._)
- GLOBAL removed for `global` (GLOBAL is deprecated).
- appveyor.yml removed (it's useless to have two CI/CD).
- Duplicate license block removed from README.md (LICENSE file exists)
- Broken and unless badges removed.

Regards, 🚀

### CODE REVIEW

**Comment by rimiti** [comment]
@mashpie It can be safely merged and released. 🤓

_Note: If you need a maintainer, I'm in!_

**Comment by SISheogorath** [comment]
@rimiti Not sure if @mashpie is reading it, I still think it would be great to have a successor for this library :)

**Comment by mashpie** [comment]
...I fucked up notifications again. 

@rimiti Thanks a lot, super helpful and crucial to proceed with maintenance
@SISheogorath Thanks for pointing...

**Comment by ccoenen** [comment]
Appveyor may have served a purpose; it is usually run in a windows environment, whereas travis has to be configured to do so manually. It could be added to the [travis config to run on Linux and Windows](https://docs.travis-ci.com/user/multi-os/)

**Pull request merged**
