### PR TITLE
updateFile directoryPermission fix

### PR DESCRIPTION
**Pull request by radarsu**
When updating a file i18n overrides its permission to 644. I think parameter directoryPermissions should also work there, or you could create another parameter updateDirectoryPermissions.

I opt for first option.

### CODE REVIEW

**Comment by mashpie** [comment]
also check with umask https://github.com/mashpie/i18n-node/pull/59

**Comment by radarsu** [comment]
Yes, I forgot about unmask so I changed
```
fs.writeFileSync(tmp, JSON.stringify(locales[locale], null, indent), {
  encofing: 'utf8',
  mode: directoryPermissions
});
```
to
```
fs.writeFileSync(tmp, JSON.stringify(locales[locale], null, indent), 'utf8');
fs.chmodSync(tmp, directoryPermissions);
```

**Comment by mashpie** [comment]
tests need to get fixed

**Comment by mashpie** [comment]
will keep as todo for refactored backend project

**Pull request closed without merging**
