### PR TITLE
YAML support

### PR DESCRIPTION
**Pull request by TheRusskiy**
Pretty much what the title says.
I find YAML format to be way more readable.

Based my changes on initial pull request by "cjroth"
- Fixed failing test (cjroth changed API to use "json" instedad of ".json"
- Added test for passing .yml to config
- Minor readme / message changes
- YAML locale example
- Found bug that if locale.js exists it overrides any locale.json and locale.yml (with extension passed explicitly)

I see that you are running tests against many node.js versions on Travis ci, inluding 0.8
It can cause issues since I used "fs.existsSync", which, I believe is a part of new API.
Anyway... CI will show. If bad things happen I'll revert to using old fs.statSync.

### CODE REVIEW

**Comment by highfeed** [comment]
I did not understand
YAML supported?

**Comment by SummerWish** [comment]
+1 for yaml support.

**Comment by PavelPolyakov** [comment]
+1 for the yaml support

**Comment by nickbuddendotcom** [comment]
+1

**Comment by gustavohenke** [comment]
Yay, almost 3 years and this is still not merged :grin:

**Comment by mashpie** [comment]
That's the deal with priorities

**Comment by gustavohenke** [comment]
Is there anything I could help with, @mashpie?

**Comment by mashpie** [comment]
well I guess, conflicts are hard to resolve now. So e fresh PR adding that feature would be most usefull, including tests & docs.

**Comment by aug-riedinger** [comment]
Well for those who don't want to wait for the PR to be merged, I wrote another translation module: https://github.com/aug-riedinger/i18n-node-yaml

I used a different approach: file organised by content instead of by language. You get:

```
# translations.yml

hello:
  world:
    en: Hello World
    fr: Bonjour le monde
foo:
  bar: Foo bar
```

instead of having both:
```
# en.yml
hello:
  world: Hello World
foo:
  bar: Foo bar
```
and
```
# fr.yml
hello:
  world: Bonjour le monde
foo:
  bar: Foo bar
```

Looking forward to having some feedback on this.

**Comment by hishammalik** [comment]
+1

**Comment by jun85664396** [comment]
+1

**Comment by mashpie** [comment]
so... although not merged directly - will keep as todo for refactored backend project

**Pull request closed without merging**
