### PR TITLE
factory functionality with the backward compatibility

### PR DESCRIPTION
**Pull request by rakhnin**
It gives us to use multiple i18n instances.

Usage: 

```js

// previous usage
var i18n = require('i18n-node')

// new usage
var I18nFactory = require('i18n-node').Factory
var i18nNew = new I18nFactory()
i18nNew.configure({
//...
});

```

### CODE REVIEW

**Comment by Bartinger** [comment]
Would be great if this gets merged. Seems like an easy way to support multiple instances

**Comment by ValiDraganescu** [comment]
I need this :)

**Comment by woodcockjosh** [comment]
Check out https://github.com/mashpie/i18n-node/pull/438. Basically solves the same problem. But yes we need this.

**Comment by mashpie** [comment]
feature is released as of 0.12.0 with some extra sugar (shortcut to i18n.configure on creation):

```js
const { I18n } = require("i18n");

const i18n = new I18n({
    locales:['en', 'de'],
    directory: __dirname + '/locales'
});
```

see https://github.com/mashpie/i18n-node/tree/master#as-instance for details

**Pull request closed without merging**
