### PR TITLE
Russian-specific plurals support added.

### PR DESCRIPTION
**Pull request by maxatwork**
In Russian language there are several forms of plurals:
 - 1 cat - 1 кошка (form 'one' used)
 - 2,3 or 4 cats - 2, 3 или 4 кошки (form 'two' used)
 - 5-20 cats - 5-20 кошек (form 'five' used)
 - 21 cats - 21 кошка (again form of 'one' used)

... and so on.

Also, added 'zero' key for more human readable outputs for 0 case (like 'there are no monkeys in the tree').

### CODE REVIEW

**Comment by highfeed** [comment]
So still do?

**Comment by kulakowka** [comment]
I need this opportunity too.

**Comment by mashpie** [comment]
won't merge but will implement similar solution

**Comment by mashpie** [comment]
https://www.npmjs.com/package/make-plural looks most promising too me

**Comment by mashpie** [comment]
alternatively could be implemented "stand-alone" by following https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html#index-plural-form-formulas

**Comment by mashpie** [comment]
and a higher level approach via https://www.npmjs.com/package/messageformat supporting CLDR following ICU standards - a bit heavy weighted but future proof

**Comment by mashpie** [comment]
any feedback on that feature draft https://github.com/mashpie/i18n-node/commit/a80287873e3ee18aeb2f3cacc385c89450524949 ?

**Comment by mashpie** [comment]
so that should help at first https://github.com/mashpie/i18n-node#i18n__mf

**Comment by Noiwex** [comment]
i dont think this works properly

**Pull request closed without merging**
