### PR TITLE
Adds parser option to allow for different storage formats

### LINKED ISSUE #487: [Discussion] Allow a parser option to customize storage format
Hello,

First of all, thank you for creating this awesome library. I would love to use it but far prefer the YAML based storage that I am used to from web frameworks like Ruby on Rails.

I see in the README it is on the roadmap to implement a storage adapter to allow for customizing this. Is this still the plan?

If so I think i have suggestion. It isn't quite a storage adapter, but looking at the code, if you added a 'parser' option which defaults to
```javascript
var parser = opt.parser || JSON
```

It would allow customization of the parser to be any object that responds to .parse and .stringify, this would make it really easy to plug in for example a YAML parser https://eemeli.org/yaml/v1/#parse-amp-stringify

What do you think of this idea? I would love to contribute and whip up a PR so you would only have to review it :)

### PR DESCRIPTION
**Pull request by mathiashsteffensen**
Will close #487

This is my first time contributing to any 'real' OSS, so please don't hold back with your critique :)

### CODE REVIEW

**Comment by mashpie** [comment]
Thank you for your contribution and fast response. I'd say you hold on a little, as today I have some minor refactoring upstream which will be conflicting and require a rebase. :)

Your changes are well focused and readable. I only have some simple points to consider:

1) add `YAML` to devDependencies  - this should fix pipeline too
2) README: Configure should outline defaults by default and give instructions on possible setting. It should mention to have `require('YAML')`
3) When writing tests, better use `new I18n({})` (like in https://github.com/mashpie/i18n-node/blob/master/test/i18n.noTraversal.js) and bind your tests to a local object

Thanks again... I'd ping as soon I am done.

**Comment by mashpie** [comment]
Alright, @mathiashsteffensen - feel free to proceed...

**Comment by guyaumetremblay** [comment]
@mathiashsteffensen @mashpie Hi! I'm really interested by this PR. Do you plan to merge it soon?

**Comment by mashpie** [comment]
yes

**Comment by mashpie** [comment]
...apply updates, resolve conflicts, retest and review. (maybe complete testing) It's a bit more than "just merging". But Okay, I'll take some time and some coffee "soon".

**Comment by guyaumetremblay** [comment]
@mashpie I was asking as the PR is 3 months old and the initiator start to update the PR also 3 months ago. So, I was asking if the work to merge it was still in progress or on hold... Sorry if my request looked like me asking to do this "ASAP".

**Comment by mashpie** [comment]
All good. No worries :) it‘s More like: Every task Taking more than some minutes will be lost… These days. So: Thanks for reminding.

**Pull request merged**
