### PR TITLE
Language fallback

### PR DESCRIPTION
**Pull request by viniciuskneves**
I was reading the issues regarding fallbacks and I've found this fork which is pretty nice and useful.

It might not be the perfect solution but it is extremely flexible on the other hand.

Would appreciate to have it on master branch.

### CODE REVIEW

**Comment by mashpie** [comment]
Nice, Thanks!

**Comment by mashpie** [comment]
despite github saying "passes" tests fail now https://travis-ci.org/mashpie/i18n-node/builds/78068889

Could you take a look at this?

**Comment by viniciuskneves** [comment]
@mashpie WIP, PR it asap :)

**Comment by mashpie** [comment]
great! Thank you

**Comment by viniciuskneves** [comment]
@mashpie https://github.com/mashpie/i18n-node/pull/171

**Pull request merged**
