### PR TITLE
Added multiple directories support

### PR DESCRIPTION
**Pull request by EddyTrotin**
i18n now support multiple sources for translations.This feature is backward compatible, check README.md for details. 
Concerning tests I add some issues with the global scope. In fact the files I added passes tests when ran alone but fails with the full test suit. That is why the Makefile test function now call mocha two times.

### CODE REVIEW

**Comment by mashpie** [comment]
Thanks a lot for this - will certainly merge soon. Just wanted to review a bit before

**Comment by JasonSi** [comment]
Merge it please~~ Thank you ~~

**Comment by simonmilz** [comment]
"will certainly merge soon" they said...

**Comment by brydda** [comment]
I really the simplicity and ease of this package vs. others. However, I need multi-directory support. 
Any chance of this work/pull or other support for placing translation files in multiple directories, being merged any time soon? Thanks @mashpie

**Comment by mashpie** [comment]
more than 3 years later I still consider merging... or well implementing similar. One concern with that PR is the multiple use of `.configure()`. Another are the conflicts with current code base. Still I see the need for supporting multidir setups.

Meanwhile you should be able to load any kind of "exotic" setup by using staticCatalog option (https://github.com/mashpie/i18n-node#some-words-on-staticcatalog-option) introduced with last release in 0.10.0.

**Comment by danielaharon** [comment]
@mashpie Thank you for the quick response. I will use the static option for now and wait for multi-dir support. 

Regarding the suggested implementation, since I spoke of simplicity in my previous post, I must admit that I found the suggested approach (current PR) more complicated than I expected. What I have in mind is just to add the ability to specify the directory parameter as an array, then treat the first directory element as input/output (for compatibility reasons) and all the rest as input only (extra search path). This would keep things both very simple and backward compatible and yet, allow one to add translation files from additional paths (e.g., for sub components). 

Does the above make sense?

**Comment by brydda** [comment]
@mashpie Thank you for the quick response. I will use the static option for now and wait for multi-dir support. 

Regarding the suggested implementation, since I spoke of simplicity in my previous post, I must admit that I found the suggested approach (current PR) more complicated than I expected. What I have in mind is just to add the ability to specify the directory parameter as an array, then treat the first directory element as input/output (for compatibility reasons) and all the rest as input only (extra search path). This would keep things both very simple and backward compatible and yet, allow one to add translation files from additional paths (e.g., for sub components). 

Does the above make sense?

**Comment by mashpie** [comment]
well... although I can not merge directly - will keep as todo for refactored backend project

**Pull request closed without merging**
