### PR TITLE
Missing Key Function (fixes #333)

### LINKED ISSUE #333: Throw an error / emit an error when unknown key is used?
Hi!

How can I get a log message / event / callback when an unknown key is attempted to be translated?  The normal behavior of simply returning the value is usually OK when requesting full strings to be translated, but with object notation, it is quite strange.

I imagine registering a callback as part of configure `onMissingKey()` would be very helpful to catch missing translations in a test suite.

### PR DESCRIPTION
**Pull request by einfallstoll**
Can be used to return static error strings (e.g. "[MISSING TRANSLATION]") to make it easy to detect by CI. Or to do have some custom error logic.

### CODE REVIEW

**Comment by mashpie** [comment]
would be perfect if you could provide a little doc in README

**Comment by einfallstoll** [comment]
I can remember to have updated the README - but I also remember a fight between me an git when doing some local merges and I probably killed the change.

... anyways: I just updated the README (again)

**Comment by mashpie** [comment]
Alright! Thanks a lot.... here we go

**Comment by mashpie** [comment]
and release to npm as 0.10.0

**Pull request merged**
