### PR TITLE
Default to 1st language if duplicate queryParam

### PR DESCRIPTION
**Pull request by Elias-Serneels**
#356 Fixes an issue with "toLowerCase" being called on an Array throwing an error.

### CODE REVIEW

**Comment by Elias-Serneels** [comment]
These builds seem to be broken. Would still love to see this bugfix in master though.

**Comment by danielcherubini** [comment]
We've been seeing this error pop up in production, of course we can catch this before it goes into the library .. but honestly the library also should check that the item is a string before trying to run string functions on it.

Please get this into master and NPM

**Comment by RhobW** [comment]
If there are multiple language query parameters but the first one is empty it still throws an exception.
Suggest either ignoring it altogether or using the first non-empty language query parameter:
https://github.com/RhobW/i18n-node

**Comment by mashpie** [comment]
closing since #442 superseeds

**Pull request closed without merging**
