### PR TITLE
fix: removed deprecated messageformat

### PR DESCRIPTION
**Pull request by calmonr**
The package `messageformat` has been deprecated in favor of `@messageformat/core`.

### CODE REVIEW

**Comment by calmonr** [comment]
@mashpie There might be breaking changes for a few people (as the validation for unused plural keys was disabled by default):

https://github.com/mashpie/i18n-node/blob/494a4648105617207f195f161daae1cb41efc769/i18n.js#L332

PRs explaining the reasons:

https://github.com/messageformat/messageformat/pull/244
https://github.com/messageformat/messageformat/pull/290

cc @eemeli

**Comment by mashpie** [comment]
Thanks @calmonr for your effort. I‘ll take some time to review those breaking changes carefully - would be the 1st break in 10 years;)

**Comment by mashpie** [comment]
I should try to keep test cases with real mf strings in json files, Russian for example plurals are complex and should still work.

**Comment by niftylettuce** [comment]
@mashpie I just sponsored you on GitHub - hopefully you can get this resolved so we can no longer have the dep warning!

**Comment by niftylettuce** [comment]
Of course @mashpie, without this project, https://forwardemail.net wouldn't have localization!

**Comment by mashpie** [comment]
This is a nice testimonial! Note to myself: … should collect them.

**Comment by mashpie** [comment]
@calmonr Thanks for PR
@niftylettuce here you go :)

https://github.com/mashpie/i18n-node/releases/tag/0.14.0

```
❯ yarn add i18n
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 14 new dependencies.
info Direct dependencies
└─ i18n@0.14.0
info All dependencies
├─ @messageformat/core@3.0.0
├─ @messageformat/date-skeleton@1.0.0
├─ @messageformat/number-skeleton@1.0.0
├─ @messageformat/parser@5.0.0
├─ @messageformat/runtime@3.0.0
├─ boolean@3.1.4
├─ debug@4.3.3
├─ fast-printf@1.6.9
├─ i18n@0.14.0
├─ math-interval-parser@2.0.1
├─ moo@0.5.1
├─ ms@2.1.2
├─ mustache@4.2.0
└─ safe-identifier@0.4.2
✨  Done in 4.58s.
```

**Comment by calmonr** [comment]
@mashpie You're most welcome.

**Pull request merged**
